"""Forecast Service — ECO AI.
Uses the real ML-based forecast pipeline instead of synthetic random noise.
"""
from datetime import datetime, timedelta, timezone
from typing import Any, Dict, List, Optional

from sqlalchemy.orm import Session

from app.services.analytics import _active_dataset, _active_dataset_info
from app.services.forecasting import generate_forecast


def _aggregate_daily_points(points: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    daily: Dict[str, Dict[str, Any]] = {}
    for point in points:
        ts = datetime.fromisoformat(point["timestamp"].replace("Z", "+00:00"))
        day_key = ts.strftime("%Y-%m-%d")
        bucket = daily.setdefault(day_key, {"date": day_key, "day_label": ts.strftime("%a, %d %b"), "values": []})
        bucket["values"].append(point["forecast_mw"])

    result: List[Dict[str, Any]] = []
    for key in sorted(daily):
        values = daily[key]["values"]
        avg_mw = round(sum(values) / len(values), 2) if values else 0.0
        peak_mw = round(max(values), 2) if values else 0.0
        min_mw = round(min(values), 2) if values else 0.0
        total_mwh = round(sum(values), 2) if values else 0.0
        result.append({
            "date": key,
            "day_label": daily[key]["day_label"],
            "is_weekend": datetime.strptime(key, "%Y-%m-%d").weekday() >= 5,
            "avg_mw": avg_mw,
            "peak_mw": peak_mw,
            "min_mw": min_mw,
            "total_mwh": total_mwh,
        })
    return result


def generate_24h_forecast(db: Session, dataset_id: Optional[int] = None) -> Dict[str, Any]:
    """Return 24-hour forecast points generated by the real ML pipeline."""
    dataset = _active_dataset(db, dataset_id)
    result = generate_forecast(db, horizon_hours=24, dataset_id=dataset_id)
    points = result.get("forecast", [])
    if not points:
        return {
            "forecast_type": "24h",
            "generated_at": datetime.now(timezone.utc).replace(tzinfo=None).isoformat() + "Z",
            "model_label": "RandomForestRegressor (chronological validation)",
            "active_dataset": _active_dataset_info(dataset),
            "horizon_hours": 24,
            "points": [],
            "summary": {
                "peak_forecast_mw": 0.0,
                "peak_hour": "N/A",
                "total_forecast_mwh": 0.0,
                "avg_forecast_mw": 0.0,
            },
            "message": result.get("message", "Insufficient data for a reliable forecast."),
        }

    total_forecast = sum(p["forecast_mw"] for p in points)
    peak_point = max(points, key=lambda p: p["forecast_mw"])
    return {
        "forecast_type": "24h",
        "generated_at": datetime.now(timezone.utc).replace(tzinfo=None).isoformat() + "Z",
        "model_label": "RandomForestRegressor (chronological validation)",
        "active_dataset": _active_dataset_info(dataset),
        "horizon_hours": 24,
        "points": [{
            "timestamp": p["timestamp"],
            "hour": p["hour"],
            "forecast_mw": p["forecast_mw"],
            "lower_ci": p["lower_mw"],
            "upper_ci": p["upper_mw"],
            "is_peak": p["is_peak"],
            "day_label": datetime.fromisoformat(p["timestamp"].replace("Z", "+00:00")).strftime("%a %H:00"),
        } for p in points],
        "summary": {
            "peak_forecast_mw": peak_point["forecast_mw"],
            "peak_hour": datetime.fromisoformat(peak_point["timestamp"].replace("Z", "+00:00")).strftime("%a %H:00"),
            "total_forecast_mwh": round(total_forecast, 2),
            "avg_forecast_mw": round(total_forecast / len(points), 2),
        },
        "message": result.get("message", "Forecast generated using the active dataset."),
    }


def generate_7d_forecast(db: Session, dataset_id: Optional[int] = None) -> Dict[str, Any]:
    """Return 7-day forecast summaries generated from the real ML forecast pipeline."""
    dataset = _active_dataset(db, dataset_id)
    result = generate_forecast(db, horizon_hours=168, dataset_id=dataset_id)
    points = result.get("forecast", [])
    if not points:
        return {
            "forecast_type": "7d",
            "generated_at": datetime.now(timezone.utc).replace(tzinfo=None).isoformat() + "Z",
            "model_label": "RandomForestRegressor (chronological validation)",
            "active_dataset": _active_dataset_info(dataset),
            "horizon_days": 7,
            "days": [],
            "message": result.get("message", "Insufficient data for a reliable forecast."),
        }

    return {
        "forecast_type": "7d",
        "generated_at": datetime.now(timezone.utc).replace(tzinfo=None).isoformat() + "Z",
        "model_label": "RandomForestRegressor (chronological validation)",
        "active_dataset": _active_dataset_info(dataset),
        "horizon_days": 7,
        "days": _aggregate_daily_points(points),
        "message": result.get("message", "Forecast generated using the active dataset."),
    }
